set nocompatible              " be iMproved, required
filetype off                  " required

syntax on
set laststatus=2
set encoding=utf-8
set ttimeoutlen=50
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

set ignorecase
set smartcase

nnoremap K i<Cr><Esc>
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" alternatively, pass a path where Vundle should install plugins
"let path = '~/some/path/here'
"call vundle#rc(path)

" let Vundle manage Vundle, required
Plugin 'gmarik/vundle'

filetype plugin indent on     " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Plugin commands are not allowed.
" Put your stuff after this line
Bundle 'bling/vim-airline'
Bundle 'tpope/vim-fugitive'
Bundle 'scrooloose/nerdtree'
Bundle 'altercation/vim-colors-solarized'

colorscheme solarized
let g:airline_powerline_fonts = 1

" NERDTree
let NERDTreeHighlightCursorline=1
map <C-n> :NERDTreeToggle<CR>
